name: climate_cast

description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For ios icons
  cupertino_icons: ^1.0.2

  # For getting lat log
  geolocator: ^11.0.0

  # For using apis
  http: ^1.2.1

  # For rotating spining animation
  flutter_spinkit: ^5.1.0

  # For showing toast
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/cloudy.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/cloudy.png"
  windows:
    generate: true
    image_path: "assets/icon/cloudy.png"
  macos:
    generate: true
    image_path: "assets/icon/cloudy.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf
          weight: 900

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700